"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load backend/.env into the environment (HF_TOKEN, etc.)
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / '.env', override=True)
except ImportError:
    pass

# Optional: HF token for downloading emotion model weights via huggingface_hub.
HUGGINGFACE_API_TOKEN = (
    os.environ.get('HUGGINGFACE_API_TOKEN', '').strip()
    or os.environ.get('HF_TOKEN', '').strip()
    or os.environ.get('HF_API_TOKEN', '').strip()
    or os.environ.get('HUGGING_FACE_API_KEY', '').strip()
)

# OpenRouter (MindSync chat proxy — browser cannot call OpenRouter directly due to CORS)
OPENROUTER_API_KEY = (
    os.environ.get('OPENROUTER_API_KEY', '').strip()
    or os.environ.get('OPENROUTER_KEY', '').strip()
)
# Set OPENROUTER_API_KEY in backend/.env (never commit real keys).
OPENROUTER_REFERER = os.environ.get('OPENROUTER_REFERER', 'http://localhost').strip() or 'http://localhost'
OPENROUTER_TITLE = os.environ.get('OPENROUTER_TITLE', 'MindSync').strip() or 'MindSync'

STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '').strip()
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '').strip()
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '').strip()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9)5&zy+jen_!7k^&=^rxd$^q*sa7+#4hq(ftn3f%yr^8+=w=$q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Local dev: bind all interfaces so phones on the same Wi‑Fi can reach Django:
#   python manage.py runserver 0.0.0.0:8000


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'users',
    'face_detection',
    'tracking.apps.TrackingConfig',
    'chat.apps.ChatConfig',
    'subscriptions.apps.SubscriptionsConfig',
    'payments.apps.PaymentsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS: DEBUG allows any origin (Flutter web uses random localhost ports; LAN devices vary).
# In production set DEBUG=False and list web app origins in CORS_ALLOWED_ORIGINS (comma-separated).
# Example: CORS_ALLOWED_ORIGINS=https://app.mindsync.com,https://www.mindsync.com
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        o.strip()
        for o in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
        if o.strip()
    ]

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Emotion API: local weights under face_detection/weights/facial_emotions (see download_emotion_weights.py)
EMOTION_MODEL_ID = os.environ.get("EMOTION_MODEL_ID", "dima806/facial_emotions_image_detection").strip()
EMOTION_WEIGHTS_DIR = Path(BASE_DIR) / "face_detection" / "weights" / "facial_emotions"
# Cap frames analyzed per uploaded video (cost / latency)
EMOTION_VIDEO_MAX_FRAMES = int(os.environ.get("EMOTION_VIDEO_MAX_FRAMES", "120"))

# Chat app scan APIs: /api/analyze-image/, /api/analyze-video/
CHAT_WEIGHTS_DIR = Path(BASE_DIR) / "chat" / "weights"
CHAT_EMOTION_HF_SUBDIR = os.environ.get("CHAT_EMOTION_HF_SUBDIR", "hf_emotion").strip()
CHAT_EMOTION_MODEL_ID = os.environ.get(
    "CHAT_EMOTION_MODEL_ID", "dima806/facial_emotions_image_detection"
).strip()
CHAT_VIDEO_MAX_FRAMES = int(os.environ.get("CHAT_VIDEO_MAX_FRAMES", "120"))

# Large video uploads (dev default)
DATA_UPLOAD_MAX_MEMORY_SIZE = min(
    int(os.environ.get("DATA_UPLOAD_MAX_MEMORY_SIZE", str(100 * 1024 * 1024))),
    2147483648,
)
FILE_UPLOAD_MAX_MEMORY_SIZE = DATA_UPLOAD_MAX_MEMORY_SIZE

# Manual bank transfer instructions shown in the Flutter payment screen.
MANUAL_PAYMENT_BANK_DETAILS = {
    'bank_name': os.environ.get('MINDSYNC_BANK_NAME', 'MindSync Partner Bank'),
    'account_title': os.environ.get('MINDSYNC_ACCOUNT_TITLE', 'MindSync Wellness Pvt Ltd'),
    'account_number': os.environ.get('MINDSYNC_ACCOUNT_NUMBER', '1234567890123456'),
    'iban': os.environ.get('MINDSYNC_IBAN', ''),
    'swift': os.environ.get('MINDSYNC_SWIFT', ''),
    'instructions': (
        'Transfer the exact plan amount. Include your username in the transfer note if possible. '
        'Then submit the transaction reference and payment screenshot in the app.'
    ),
}


from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}