// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKQFPE1WnCk1z-rUB5iNya34fSUhjPdZs',
    appId: '1:785569217251:web:c1de5d7ff4597f3ae1e3d6',
    messagingSenderId: '785569217251',
    projectId: 'mindsync-c6917',
    authDomain: 'mindsync-c6917.firebaseapp.com',
    storageBucket: 'mindsync-c6917.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj4NVRUmrcgixhlk49LwIJmTH2p32bfrM',
    appId: '1:785569217251:android:25e0ceb69c220c12e1e3d6',
    messagingSenderId: '785569217251',
    projectId: 'mindsync-c6917',
    storageBucket: 'mindsync-c6917.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFXQGbLddSHMSF8aItp-cshEUXqu3ZnYQ',
    appId: '1:785569217251:ios:e49b12a62519b76de1e3d6',
    messagingSenderId: '785569217251',
    projectId: 'mindsync-c6917',
    storageBucket: 'mindsync-c6917.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFXQGbLddSHMSF8aItp-cshEUXqu3ZnYQ',
    appId: '1:785569217251:ios:e49b12a62519b76de1e3d6',
    messagingSenderId: '785569217251',
    projectId: 'mindsync-c6917',
    storageBucket: 'mindsync-c6917.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKQFPE1WnCk1z-rUB5iNya34fSUhjPdZs',
    appId: '1:785569217251:web:2e02a6335dd8ed99e1e3d6',
    messagingSenderId: '785569217251',
    projectId: 'mindsync-c6917',
    authDomain: 'mindsync-c6917.firebaseapp.com',
    storageBucket: 'mindsync-c6917.firebasestorage.app',
  );
}
